### ISSUE TITLE
Browser errors bubbling

### ISSUE THREAD

**Issue by vaseker** [catberry/catberry#183] opened 2015-07-30 21:14 UTC
Because of `return` in global error [event handler](https://github.com/catberry/catberry/blob/develop/browser/Bootstrapper.js#L99) there is no possible to handle errors in expected places.
E.g.: `UHR.request('/foo/bar/).then(handleOk).catch(handleFIAL)` - errored response will not handled by `handleFIAL` as expected.

**Comment by pragmadash** [comment] 2015-07-31 03:57
```javascript```
UHR.request('/foo/bar/`)
  .then(handleOk)
  .catch(handleFIAL)
```
This code is always handling any connection errors in `.catch(foo)` handler. If you mean 4xx-5xx errors they don't throw exceptions. You should check `result.code` property instead and can throw your own errors if you want.

**Any** error in **any** asynchronous Catberry's code is handled by `.catch(foo)` handler because everything works using Promises. Global error suppressing should not be a developer's problem because global errors should not occur at all therefore they just are logged as `FATAL` errors.

**Comment by vaseker** [comment] 2015-07-31 06:21
Thank you. That's it. I'm expecting 4xx-5xx as reject state of promise.
31 июля 2015 г. 8:57 пользователь "Denis Rechkunov" <
notifications@github.com> написал:

**Comment by pragmadash** [comment] 2015-07-31 09:55
It seems like the issue is resolved, closing.

**Closed by pragmadash** 2015-07-31 09:55 UTC
Labels: question

**Comment by pragmadash** [comment] 2015-07-31 10:23
I think I should explain a little bit about the approach used with 4xx-5xx codes. 

The point is that occasionally you need to read the response body from the server with detailed information about the error (error codes, reason etc.) even when you have 4xx-5xx HTTP response code. 

For example, jQuery AJAX does not allow to read the response body in such situation it just throws an exception or rejects deferred object. I think it's wrong approach therefore Catberry UHR was implemented with the ability to read the response body even with an error response.
